import { describe, it, expect } from 'vitest'
import { toCurl, toCurlScript } from '@/utils/curlGenerator'
import type { CapturedRequest } from '@/types/requests'
import type { RedactConfig } from '@/types/config'

function makeReq(over: Partial<CapturedRequest> = {}): CapturedRequest {
  return {
    id: 'r1',
    kind: 'fetch',
    method: 'POST',
    url: 'https://api.example.com/foo',
    requestHeaders: { 'Content-Type': 'application/json' },
    requestBody: null,
    status: 200,
    ok: true,
    responseHeaders: {},
    responseBody: null,
    responseSizeBytes: 0,
    startTime: 0,
    duration: 10,
    startedAt: '2026-05-21T00:00:00.000Z',
    ...over
  }
}

const cfg: RedactConfig = {
  headerKeys: ['authorization', 'cookie', 'x-api-key'],
  bodyKeys: ['password', 'token', 'api_key'],
  maskPasswordInputs: true
}

describe('toCurl', () => {
  it('GET 无 body 时不加 --data-raw', () => {
    const c = toCurl(makeReq({ method: 'GET', url: 'https://x.com/y', requestHeaders: {}, requestBody: null }), cfg)
    expect(c).toBe(`curl -X GET 'https://x.com/y'`)
  })

  it('POST + JSON body 渲染 --data-raw 单引号包裹', () => {
    const c = toCurl(makeReq({
      requestHeaders: { 'Content-Type': 'application/json' },
      requestBody: '{"name":"foo"}'
    }), cfg)
    expect(c).toContain(`curl -X POST 'https://api.example.com/foo'`)
    expect(c).toContain(`-H 'Content-Type: application/json'`)
    expect(c).toContain(`--data-raw '{"name":"foo"}'`)
  })

  it('header 命中 redact.headerKeys → 值被 *** 化（大小写不敏感）', () => {
    const c = toCurl(makeReq({
      requestHeaders: { Authorization: 'Bearer sk_real_secret', 'X-API-Key': 'real', 'X-Other': 'keep' }
    }), cfg)
    expect(c).toContain(`-H 'Authorization: ***'`)
    expect(c).toContain(`-H 'X-API-Key: ***'`)
    expect(c).toContain(`-H 'X-Other: keep'`)
    expect(c).not.toContain('sk_real_secret')
  })

  it('URL query 命中 redact.bodyKeys → 值被 *** 化', () => {
    const c = toCurl(makeReq({
      method: 'GET', requestBody: null,
      url: 'https://api.example.com/foo?token=real_token&name=keep'
    }), cfg)
    expect(c).toContain('token=***')
    expect(c).toContain('name=keep')
    expect(c).not.toContain('real_token')
  })

  it('JSON body 里命中 bodyKeys 的字段值被 *** 化', () => {
    const c = toCurl(makeReq({
      requestBody: '{"password":"hunter2","name":"foo","api_key":"sk_xx"}'
    }), cfg)
    expect(c).toContain('"password":"***"')
    expect(c).toContain('"api_key":"***"')
    expect(c).toContain('"name":"foo"')
    expect(c).not.toContain('hunter2')
    expect(c).not.toContain('sk_xx')
  })

  it('body 里嵌套对象也走脱敏', () => {
    const c = toCurl(makeReq({ requestBody: '{"data":{"password":"x","keep":"y"}}' }), cfg)
    expect(c).toContain('"password":"***"')
    expect(c).toContain('"keep":"y"')
  })

  it('URL / header / body 里单引号 escape 成 \\\'（防 shell 截断）', () => {
    // bash 单引号串中遇到 ' 必须 ' + \' + ' 三段拼起来才能续上字面值
    const c = toCurl(makeReq({
      url: `https://x.com/it's-ok`,
      requestHeaders: { 'X-Note': `o'reilly` },
      requestBody: `{"q":"a'b"}`
    }), cfg)
    expect(c).toContain(`'https://x.com/it'\\''s-ok'`)
    expect(c).toContain(`'X-Note: o'\\''reilly'`)
    expect(c).toContain(`'{"q":"a'\\''b"}'`)
  })

  it('method 缺省 / 小写 → 输出大写', () => {
    const c = toCurl(makeReq({ method: 'put' }), cfg)
    expect(c).toContain('curl -X PUT')
  })

  it('多个 header 各自一行 + 末尾续行符', () => {
    const c = toCurl(makeReq({
      requestHeaders: { A: '1', B: '2' },
      requestBody: '{}'
    }), cfg)
    // 行末必须是 ` \` 才能让 bash 续行
    const lines = c.split('\n')
    expect(lines[0]).toMatch(/ \\$/)
    expect(lines.length).toBeGreaterThanOrEqual(3)
  })

  it('空 body 与 null body 都不输出 --data-raw', () => {
    expect(toCurl(makeReq({ requestBody: '' }), cfg)).not.toContain('--data-raw')
    expect(toCurl(makeReq({ requestBody: null }), cfg)).not.toContain('--data-raw')
  })
})

describe('toCurlScript', () => {
  it('空数组时输出 header + "no requests" 占位', () => {
    const s = toCurlScript([], cfg, { generatedAt: 'T', mooVersion: '0.2.0' })
    expect(s).toContain('#!/bin/sh')
    expect(s).toContain('Generated by Moo v0.2.0 at T')
    expect(s).toContain('0 request(s)')
    expect(s).toContain('(no requests captured)')
  })

  it('多条 request 之间空行隔开 + 序号注释', () => {
    const s = toCurlScript([
      makeReq({ id: 'r1', method: 'GET', url: 'https://a/1', status: 200 }),
      makeReq({ id: 'r2', method: 'POST', url: 'https://b/2', status: 500 })
    ], cfg, { generatedAt: 'T' })
    expect(s).toContain('# [1/2] GET https://a/1 → 200')
    expect(s).toContain('# [2/2] POST https://b/2 → 500')
    // 两条 curl 命令各自存在
    expect(s.match(/curl -X /g)?.length).toBe(2)
  })

  it('版本号缺省时 header 不带 vX', () => {
    const s = toCurlScript([], cfg, { generatedAt: 'T' })
    expect(s).toContain('Generated by Moo at T')
    expect(s).not.toContain(' v')
  })
})
