import type { CapturedRequest } from '@/types/requests'
import type { RedactConfig } from '@/types/config'
import { redactUrl, redactHeaders, redactBody } from './redact'

/**
 * 把 CapturedRequest 渲染成可粘到终端复现的 curl 命令。
 * 走 redact：header / URL query / body 三处的命中字段一律 *** 化，
 * 不会把用户的真实凭据吐到禅道附件里。
 */
export function toCurl(req: CapturedRequest, cfg: RedactConfig): string {
  const url = redactUrl(req.url, cfg.bodyKeys)
  const headers = redactHeaders(req.requestHeaders, cfg.headerKeys)
  const body = redactBody(req.requestBody, cfg.bodyKeys)
  const method = (req.method || 'GET').toUpperCase()

  const parts: string[] = [`curl -X ${method} ${shellEscape(url)}`]
  for (const [k, v] of Object.entries(headers)) {
    parts.push(`  -H ${shellEscape(`${k}: ${v}`)}`)
  }
  if (body !== null && body !== '') {
    parts.push(`  --data-raw ${shellEscape(body)}`)
  }
  return parts.join(' \\\n')
}

/**
 * 把多条 request 拼成一份可保存的 .curl.sh 文件内容。
 * 头部注释带生成时间 + 条数；条与条之间空行隔开。
 */
export function toCurlScript(
  reqs: CapturedRequest[],
  cfg: RedactConfig,
  opts: { generatedAt?: string; mooVersion?: string } = {}
): string {
  const generatedAt = opts.generatedAt ?? new Date().toISOString()
  const version = opts.mooVersion ? ` v${opts.mooVersion}` : ''
  const header = [
    '#!/bin/sh',
    `# Generated by Moo${version} at ${generatedAt}`,
    `# ${reqs.length} request(s)`,
    '# Sensitive headers / body fields are *** redacted per project redact config.',
    ''
  ].join('\n')
  if (reqs.length === 0) return header + '# (no requests captured)\n'
  const body = reqs
    .map((r, i) => `# [${i + 1}/${reqs.length}] ${r.method} ${r.url} → ${r.status}\n${toCurl(r, cfg)}`)
    .join('\n\n')
  return header + body + '\n'
}

/**
 * Bash 单引号包裹 + 内部单引号 escape（标准 '\'' 技法）。
 * 单引号里任何字符都是字面量，唯一需要处理的就是单引号本身。
 */
function shellEscape(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`
}
